module.exports = {
  semi: true,
  tabWidth: 2,
  rangeStart: 0,
  useTabs: false,
  printWidth: 200,
  endOfLine: 'auto',
  singleQuote: true,
  proseWrap: 'never',
  insertPragma: false,
  requirePragma: false,
  bracketSpacing: true,
  trailingComma: 'es5',
  jsxSingleQuote: false,
  arrowParens: 'always',
  quoteProps: 'as-needed',
  jsxBracketSameLine: false,
  vueIndentScriptAndStyle: true,
  htmlWhitespaceSensitivity: 'strict',
};
